### =====================================
### Admin - Study Hall & Room API Test
### =====================================

@host = http://localhost:8080

### 0. 관리자 로그인 (토큰 획득)
POST {{host}}/api/login
Content-Type: application/json

{
  "username": "admin01",
  "password": "123456789"
}

> {%
    client.global.set("admin_token", "Bearer " + response.body.data.accessToken);
%}

### 1. 스터디 홀 생성 (POST)
POST {{host}}/api/v1/admin/studyhalls
Content-Type: application/json
Authorization: {{admin_token}}

{
  "name": "강남 1호점",
  "description": "조용하고 집중하기 좋은 공간입니다.",
  "simpleAddress": "강남역 1번 출구",
  "address": "서울특별시 강남구 강남대로 396",
  "latitude": 37.4979,
  "longitude": 127.0276,
  "thumbnail": "https://example.com/thumbnail.jpg",
  "openTime": "2025-07-23T09:00:00",
  "closeTime": "2025-07-23T23:00:00"
}

> {%
    // 요청 성공 시, 응답 body의 id 값을 studyHallId 라는 변수에 저장합니다.
    client.global.set("studyHallId", response.body.id);
%}

### 2. 전체 스터디 홀 조회 (GET)
GET {{host}}/api/v1/admin/studyhalls
Authorization: {{admin_token}}


### 3. 특정 스터디 홀 상세 조회 (GET)
GET {{host}}/api/v1/admin/studyhalls/1
Authorization: {{admin_token}}

### 4. 개별 스터디 룸 생성
POST {{host}}/api/v1/admin/studyhalls/1/rooms
Content-Type: application/json
Authorization: {{admin_token}}

{
  "name": "4인실 C",
  "maxNum": 4
}

> {%
    client.global.set("studyRoomId", response.body.id);
%}


### 5. 특정 홀에 속한 룸 목록 조회
GET {{host}}/api/v1/admin/studyhalls/{{studyHallId}}/rooms
Authorization: {{admin_token}}